### ISSUE TITLE
Proposed Economic Path Forward for Parrot Protocol & PRT

### ISSUE THREAD

**Issue by FrankInvestments** [gopartyparrot/feedback-flywheel#2]
This plan looks at resolving the ongoing conflict of Parrot Protocol’s lack of value creation for PRT and the debate as regards to the investment of the treasury. This proposal suggests a division of the treasury funds so as to provide the three major stakeholders (PRT holders, the team, and the VCs) a more optimal solution than the status quo. 

### Summary of Solution:

- Team to receive full protocol ownership, $7.5m, and all Seed Investments
- VCs to receive ~$13.1m for unvested tokens
- PRT Holders/Retail to receive $0.00694367 per PRT for a cumulative distribution of ~$57.6m

See below for details on calculation, fairness, and next steps

### **Background:**

Parrot Protocol (formerly Party Parrot) launched in the summer of 2021 during the boom of Solana’s “DeFi Summer”. Its vaults offered an outstanding investment opportunity to use leveraged yield farms with no liquidation risk. The team had built the protocol off of $5m of VC funds at a valuation of $25m in May of 2021.

Parrot Protocol was a huge success, attracting $400m+ of TVL, all without its own governance token or any additional incentives. In September of 2021, it held its IDO (token named PRT) at the very height of Solana’s first massive run up. The protocol was valued at $800m+, a dramatic valuation but not unusual at the time and reflective of the rapid TVL growth and the quality of the product the team had built and the speed at which it was developed & upgraded. The IDO brought $70m into the treasury and guaranteed Parrot Protocol could write its own destiny. 

PRT unfortunately quickly traded below IDO. Many theories were put forward as to why – VC dumping, free CEX tokens being dumped, SOL pullback, slowed development – but ultimately it was a combination of all the above that led PRT to be a “down-only” token, save a brief rebound at SOL’s peak. 

Post-IDO saw development almost halt while communication and excitement slowed. Much time was spent on damage control from unhappy investors and TVL declined both due to market trend and falling value proposition. “Staking” was launched but heavily restricted users from selling and seemed to derive yield predominately from inflation rather than revenue.

Since then the team focused efforts elsewhere, developing two affiliated protocols (BunnyDucky & Penguin) which supported Parrot Protocol but have done little to add value to PRT. Similarly, a number of venture investments in the Solana ecosystem have been made with the treasury funds but not much else is known on how those function. Otherwise, the treasury appears to have sat in stablecoins and not been used to generate any yield (either for growth or distribution). 

As of recent the team have re-engaged with the community but the overall sentiment has failed to improve as promises by the team to “do more”, “invest the treasury”, and “provide value to PRT” have seen little actual action. This has led to calls by PRT holders to shut down the protocol and simply redeem the treasury as it’s approximately 4 to 5x the current fully diluted valuation (FDV). The token is down approximately 98.1% from IDO.

### **Problem:**

The market currently values PRT at magnitudes less than the treasury – implying that the market expects the team’s continued operation of the protocol to be highly value destructive or that PRT holders will not see the benefit of the large treasury or its earnings.

Given the protocol’s track record, major retail holders would like the treasury to be used for token buybacks which would allow them to recover on their investments. The team meanwhile has little incentive to do this as the treasury provides job security and their tokens are still vesting. They’ve also voiced the desire to continue building the “Parrot Ecosystem”. The VCs sit in a middle position but overall are waiting for vesting like the team.

### **Proposed Solution:**

The below proposal looks at addressing each stakeholder’s primary desires in a fair manner given where we are today. Each party will be making a sacrifice from the best possible outcome for them but stands to be much better off than they are today.

**The Team**

The team will receive the below:

- 100% ownership of all code, work product, and functionality of Parrot Protocol, BunnyDucky (to the extent not owned by BUD holders), and Penguin 
- 100% ownership of Seed Investments made by the treasury in the amount of $3,537,000 of invested funds (based on Treasury Report)
- A cash distribution from the treasury in the amount of $7.5m in exchange for any remaining unvested tokens and a “Yes” vote on this proposal
- The right to cash in any vested but still owned tokens at the “Retail” category price

This allows the team to continue building the Parrot Ecosystem to the extent desired and receive all benefits from such work. Additionally it removes the negative influence of PRT holders and distraction of token price in a protocol where the token serves no purpose. 

Lastly, the cash payment provides 10+ years of runway (based on $720k annual burn) and generous compensation along with large potential upside from the Seed Investments. This leaves the team little reason not to take the deal outside of wanting to run out the vesting clock at the expense of current PRT holders.

**The VCs**

The VCs have a fiduciary duty to their investors to maximize returns. Thus it’s highly likely they’ve been a consistent negative price driver, as at IDO they were up 32x+ on their investment. Amazingly, the unvested portion of the investment (which still has 2+ years remaining for full vesting) is currently underwater. Thus the VCs stand to make a significant gain by taking payout for any unvested tokens now as it’ll greatly boost their IRR and allow reinvestment into other projects at a favorable time in the market.

The VCs will receive the below:

- A cash payment at 75% of the PRT Holder/Retail cash out rate (estimated to be $13.1m total) in exchange for any remaining unvested tokens and a “Yes” vote on this proposal
- The right to cash in any vested but still owned tokens at the “Retail” category price

This provides the VCs immediate liquidity at far above market value for their unvested tokens in exchange for taking a slightly non-proportional share of the treasury cash out. This certainty and accelerated liquidity should more than compensate for difference. This is also an approximately 437% return on the respective initial investment of $3m ($5m * 60% unvested).

_Estimate Calculation Detail_

20% ownership with ~60% unvested = ~2.52bn unvested tokens times 75% times $0.00694367 = $13.1m

60% unvested based on 10% upfront unlock and 3 year bi-monthly on remainder and ~1 year passing

**PRT Holders/”Retail”**

Many, if not most, PRT Holders are down 90%+ on their investment. Actions to date suggest little will change absent a material redemption of the treasury. No proposal can come close to repaying the original IDO price but that is irrelevant as it was set based on speculative hype and excess.

The PRT Holders/Retail will receive the below:

- A cash payment of $0.00694367 per PRT for a cumulative distribution of ~$57.6m

This payment uses the assumption of 8.3bn circulating PRT which may be inflated by any circulating Protocol Incentives, Ecosystem & Partnership, or Protocol Controlled Reserve tokens that are in the “circulating” but in the treasury (“Operating Tokens”) or deflated by non-consideration of yPRT.

This represents a 9.5x increase over the current market value and far more than can be plausibly assumed by even the team’s best efforts at changing the status quo. No amount of revenue growth will compete on a present value basis.

_Estimate Calculation Detail_

8,300,295,608.16 listed on Solscan (https://solscan.io/token/PRT88RkA4Kg5z7pKnezeNH4mafTvtQdfFgpQTGRjz44)

$0.00694367 cash out price based on $78,255,987.45 in treasury less $7,500,000 payment to the team, divided by (8.3bn tokens circulating plus weight-adjusted 1.89bn owned by VCs)

**Next Steps:**

This proposal should be reviewed and discussed by all 3 sets of stakeholders. The team should provide clarifying data on the below points within the next 7 days:

- % still vesting for Team
- % still vesting for VCs
- Correct circulating PRT figure (to include yPRT as well)
- Current Treasury liquid value

The team should inform the VCs of the proposal so they can evaluate and confirm acceptance. 

Assuming receptive feedback from the PRT Holders in the discord, I will update with fresh numbers from the team. The team will then announce the proposed “Transformation Transaction” on twitter and invite all PRT holders to join the discord for discussion. 

A vote for PRT Holders will then be held in the 1m-club channel or the team will promptly build a voting tool for PRT Holders whereby a majority of the votes will determine the outcome. The voting period will last 2 weeks so sufficient time is made for all who want to participate. 

Should the vote pass, the team will build a cashout tool whereby PRT & yPRT can be redeemed at a fixed rate plus a “Residual” token. The cashout tool will be left available for 6 months, after which any remaining funds will be proportionally claimable by Residual token holders indefinitely. 

The goal is to complete the vote and take the resulting action by August end. 

### Personal Background:

I’ve followed Parrot Protocol since the early days of its launch (back when 101% collateral was available). I’m been a member of the discord but stayed silent as I was just there to stay informed. I did not participate in the IDO as I felt the price was too high compared to other opportunities off Solana. I progressively bought and staked PRT as the price fell to “acceptable” levels but I’m down at least 80% still. I was an avid user of the protocol until yield became unsteady (due to veSBR), the UST crash, and stability fee implementation.

While it may seem that PRT Holders are getting the worst deal (still large losses compared to other parties receiving large profits), I truly believe the above is a fair resolution for all parties given everyone’s incentives. We cannot compare this to the IDO or what we bought in at; we must compare with what the price is now and what recovery looks like without this solution.

**Comment by defactojob** [comment]
While we welcome proposals with respect to improving features and tokenomics, closing the protocol is out of scope.
